[package]
name = "{{PROJECT_NAME}}-schemas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
molecule = "0.7.2"
trampoline-sdk = {git = "https://github.com/WilfredTA/trampoline", branch = "develop"}